
GET http://localhost:8000/api/products/ HTTP/1.1

###

GET http://localhost:8000/api/products/17/ HTTP/1.1

###

PUT http://localhost:8000/api/products/17/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0ODgwNzI2LCJpYXQiOjE3NDQ4ODA0MjYsImp0aSI6IjE3MTlhZGM4OWE0NjRlZTliZjYzZDc4NTdkZjllOGIyIiwidXNlcl9pZCI6MX0.dp0JFr3ZwuvNde3aKff48wNejsihYSBA0T0A5HXcR2Y

{
  "name": "Sixth product",
  "description": "amazing product!!!!",
  "price": "999.00",
  "stock": 1
}

###

DELETE http://localhost:8000/api/products/18/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0ODgwNzI2LCJpYXQiOjE3NDQ4ODA0MjYsImp0aSI6IjE3MTlhZGM4OWE0NjRlZTliZjYzZDc4NTdkZjllOGIyIiwidXNlcl9pZCI6MX0.dp0JFr3ZwuvNde3aKff48wNejsihYSBA0T0A5HXcR2Y

###

POST http://localhost:8000/api/products/ HTTP/1.1
Content-Type: application/json

{
    "name": "New Product",
    "price": 19.99,
    "description": "A new product description",
    "stock": 10
}

###

GET http://localhost:8000/api/user-orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0ODc4OTg0LCJpYXQiOjE3NDQ4Nzg2ODQsImp0aSI6IjIwZmQzZDhkNTBhZTRhMTM4ZWYzNzUwMWY5MjBjMGRmIiwidXNlcl9pZCI6Mn0.BzCPLQBmysrp_MVg9jr06zVkY0SRmM1ubvQv9tNMWLI

###

POST http://localhost:8000/api/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0ODc4OTA1LCJpYXQiOjE3NDQ4Nzg2MDUsImp0aSI6ImU2ZGZkNDBhYTk4NzQxYWViOTJkODU4YmI4Yjc4ZGU4IiwidXNlcl9pZCI6MX0.wIRoTTBs-zJsAvWJnoAoC0LtU4klzob42DoWZuePfHE

{
    "name": "New Product 3",
    "price": 39.99,
    "description": "A new product description",
    "stock": 10
}

### 

POST http://localhost:8000/api/token HTTP/1.1
Content-Type: application/json

{
    "username": "admin",
    "password": "test"
}

