GET http://localhost:8000/api/products/ HTTP/1.1

###

POST http://localhost:8000/api/products/ HTTP/1.1
Content-Type: application/json

{
    "name": "New Product",
    "price": 19.99,
    "description": "A new product description",
    "stock": 10
}
