
GET http://localhost:8000/api/products/ HTTP/1.1

###

GET http://localhost:8000/api/products/17/ HTTP/1.1

###

PUT http://localhost:8000/api/products/17/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0ODgwNzI2LCJpYXQiOjE3NDQ4ODA0MjYsImp0aSI6IjE3MTlhZGM4OWE0NjRlZTliZjYzZDc4NTdkZjllOGIyIiwidXNlcl9pZCI6MX0.dp0JFr3ZwuvNde3aKff48wNejsihYSBA0T0A5HXcR2Y

{
  "name": "Sixth product",
  "description": "amazing product!!!!",
  "price": "999.00",
  "stock": 1
}

###

DELETE http://localhost:8000/api/products/18/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0ODgwNzI2LCJpYXQiOjE3NDQ4ODA0MjYsImp0aSI6IjE3MTlhZGM4OWE0NjRlZTliZjYzZDc4NTdkZjllOGIyIiwidXNlcl9pZCI6MX0.dp0JFr3ZwuvNde3aKff48wNejsihYSBA0T0A5HXcR2Y

###

POST http://localhost:8000/api/products/ HTTP/1.1
Content-Type: application/json

{
    "name": "New Product",
    "price": 19.99,
    "description": "A new product description",
    "stock": 10
}

###

GET http://localhost:8000/api/user-orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0ODc4OTg0LCJpYXQiOjE3NDQ4Nzg2ODQsImp0aSI6IjIwZmQzZDhkNTBhZTRhMTM4ZWYzNzUwMWY5MjBjMGRmIiwidXNlcl9pZCI6Mn0.BzCPLQBmysrp_MVg9jr06zVkY0SRmM1ubvQv9tNMWLI

###

POST http://localhost:8000/api/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0ODk3MTU4LCJpYXQiOjE3NDQ4OTY4NTgsImp0aSI6ImRkZjUwOTcyMmU3YTRlNDhhNzRkMGI0MDRlZDFkNDFkIiwidXNlcl9pZCI6MX0.nIXax-K0TpJqs-s1RDyBZVTuKWFp_-T9vU51Ug3rA5M

{
    "name": "New Product 3",
    "price": 39.99,
    "description": "A new product description",
    "stock": 10
}

### 

POST http://localhost:8000/api/token HTTP/1.1
Content-Type: application/json

{
    "username": "kuaz",
    "password": "test"
}

###

GET http://localhost:8000/api/orders/ HTTP/1.1

###

GET http://localhost:8000/api/orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0OTAzODMwLCJpYXQiOjE3NDQ5MDAyMzAsImp0aSI6IjFjZTg2NWIwOGZiMzQ3MTFhMDA0ZTFmZGRjOGZmNDRmIiwidXNlcl9pZCI6Mn0.grHjZZnsdn-8GUykla_6t1Wm-WovLiCMmQ_Ev5hDXMs

###
PUT http://localhost:8000/api/orders/29a19949-f9a6-4e47-bacc-c0b1d2a15d95/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0OTEzNTAzLCJpYXQiOjE3NDQ5MDk5MDMsImp0aSI6ImMwMjYzZTUwZGE0NzQzYjNhYzFlZmY5YzY4N2U3YzIxIiwidXNlcl9pZCI6Mn0.fWX0mVw-FWvAmUBDveAWtbpxTV4TgpdCrwUgo0wsEY0

{
    "items": [
        {
            "product": 21,
            "quantity": 2
        },
        {
            "product": 22,
            "quantity": 10
        }
    ]
}

###

DELETE http://localhost:8000/api/orders/9f4c1325-738a-47d2-962a-fa709833f631/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0OTAzODMwLCJpYXQiOjE3NDQ5MDAyMzAsImp0aSI6IjFjZTg2NWIwOGZiMzQ3MTFhMDA0ZTFmZGRjOGZmNDRmIiwidXNlcl9pZCI6Mn0.grHjZZnsdn-8GUykla_6t1Wm-WovLiCMmQ_Ev5hDXMs

###

POST http://localhost:8000/api/orders/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ0OTEzNTAzLCJpYXQiOjE3NDQ5MDk5MDMsImp0aSI6ImMwMjYzZTUwZGE0NzQzYjNhYzFlZmY5YzY4N2U3YzIxIiwidXNlcl9pZCI6Mn0.fWX0mVw-FWvAmUBDveAWtbpxTV4TgpdCrwUgo0wsEY0

{
    "items": [
        {
            "product": 21,
            "quantity": 2
        }
    ]
}