# Generated by Django 5.2 on 2025-04-16 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderitem",
            old_name="produce",
            new_name="product",
        ),
    ]
